name: Build APK

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK (Java 17)
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Grant execute permission to Gradlew
        run: chmod +x ./gradlew

      - name: Build APK
        run: ./gradlew assembleRelease

      - name: Debug Build Outputs (Check APK Exists)
        run: ls -R app/build/outputs/apk/

      - name: Delete Existing Tag (if exists)
        run: |
          git tag -d v1.0 || true
          git push origin --delete v1.0 || true
        continue-on-error: true

      - name: Upload APK (Main Branch)
        if: github.ref == 'refs/heads/main'
        uses: ncipollo/release-action@v1
        with:
          artifacts: "app/build/outputs/apk/release/*.apk"
          token: ${{ secrets.PAT_TOKEN }}
          tag: v1.0
          name: "Release v1.0"
          draft: false
          prerelease: false
          replacesArtifacts: true

      - name: Upload APK (Develop Branch)
        if: github.ref == 'refs/heads/develop'
        uses: actions/upload-artifact@v4
        with:
          name: APK-Develop
          path: app/build/outputs/apk/release/*.apk